version: '2.1'
services:
  db:
    image: microsoft/mssql-server-windows-developer
    environment:
      - sa_password=Password1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password1", "-Q", "select 1" ]
      interval: 1s
      retries: 30

  web:
    image: masnider/musicstoreweb:v1
    environment:
      - Data:DefaultConnection:ConnectionString=Server=db,1433;Database=MusicStore;User Id=sa;Password=Password1;MultipleActiveResultSets=True
    ports:
      - "80:8080"

networks:
  default:
    external:
      name: nat
